<!--Andrew Robson - w16011147-->
<!--this file will perform the javascript for the orderBooksForm-->
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
    <link rel="stylesheet" href="styling.css"> <!--Links the stylesheet-->
	<title>Order Books Form</title>
</head>
<body>


<?php
require_once ('functions.php'); //links this page to the functions.php page
ini_set("session.save_path", "/home/unn_w16011147/sessionData"); //initialises the session data
session_start(); //starts a session
displayLoginLogout(); //displays the logout functionality
displayNav(); //displays the navigation functionality

if (checkLogin()) //if the user is logged in, proceed
{
    /* This code dynamically generates a web page containing a form designed with the html required to display one
    checkbox for each of the books currently held in the nbc_books database table has been provided for you in the
    assessment section for the module on blackboard. The user can select one or more books that they are interested in
    ordering by clicking the checkboxes.
    Use the browser to look at the structure of the html generated by the php code. */

    $url  = "http://unn-izge1.newnumyspace.co.uk/KF5002/assessment/orderBooksFormInc.php";
    $curl = curl_init($url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
    $result = curl_exec($curl);
    curl_close($curl);
    echo $result;
}
else
{
    echo "<p>You must be logged in to access this content.</p>\n";
}
?>

<!-- Here you need to add Javascript or a link to a script to process the form as required for the assignment -->

<script type="text/javascript">
    //<![CDATA[
    'use strict';

    window.addEventListener('load', function initialise() //when the window first loads, call the initialise function
    {
        var form = document.getElementById('orderForm'); //declares 'orderForm' as the object: 'form'
        //calls 'dataValidation' function when a change is made within the form
        form.addEventListener('change', dataValidation);
        //calls 'dataValidation' function when a change is made on forename
        form.forename.addEventListener('change', dataValidation);
        //calls 'dataValidation' function when a change is made on surname
        form.surname.addEventListener('change', dataValidation);
        //calls 'dataValidation' function when a change is made on companyName
        form.companyName.addEventListener('change', dataValidation);
        //hides the customer detail fields because they automatically appear on startup
        form.querySelector('#retCustDetails').style.visibility = "hidden";
        form.total.value = "0.00"; //states the form.total.value as being "0.00"

        /*
            this function performs the functionality to alter the text in line with the
            terms and conditions checkbox
         */
        function changeTermsAndConditions()
        {
            var termAndCond = form.termsChkbx; //converts form.termsChkbx into a variable
            //converts the text in line with the checkbox into a variable
            var textLine = form.querySelector('#termsText');

            if (termAndCond.checked) //if the checkbox has been ticked then proceed
            {
                textLine.style.color = '#000000'; //makes the font colour black
                textLine.style.fontWeight = '400'; //makes the boldness normal

                return true;
            }
            else
            {
                textLine.style.color = '#ee000b'; //makes the font colour red
                textLine.style.fontWeight = '700'; //makes the font style bold

                return false;
            }
        }

        /*
            This function is used to validate the input fields that the user will be utilising
            it hides and makes the input fields visible
            it also checks the length of the data input to test it
         */
        function userOption()
        {
            var customerOption = form.customerType; //converts form.customerType into a variable: customerOption
            //allows for access to the "hidden" field so we can alter it
            var customer = form.querySelector('#retCustDetails');
            //allows for access to the "hidden" field so we can alter it
            var trade = form.querySelector('#tradeCustDetails');

            if (customerOption.value === "") //if nothing has been selected (because the string is empty) proceed
            {
                customer.style.visibility = "hidden"; //change the visibility to hidden
                trade.style.visibility = "hidden"; //change the visibility to hidden

                return false;
            }
            else if (customerOption.value === "ret") //if the value = "ret" then proceed
            {
                customer.style.visibility = "visible"; //show the customer input fields
                trade.style.visibility = "hidden"; //hide the companyName input field

                //trim both of the variables and check if it is empty
                if (form.forename.value.trim === '' || form.surname.value.trim() === '')
                {
                    return false;
                }

                return true;
            }
            else if (customerOption.value === "trd") //if the value = "trd", proceed
            {
                customer.style.visibility = "hidden"; //hide the customer fields
                trade.style.visibility = "visible"; //show the companyName field

                if (form.companyName.value.trim === '') //trim the companyName field and check if it is empty
                {
                    return false;
                }

                return true;
            }
        }

        /*
            this function will be used to validate all of the data at once, deciding whether the user can submit or not
         */
        function dataValidation()
        {
            var purchase = productPrice(); //convert the function result to the variable: purchase
            //convert the function result to the variable: termsAndconditions
            var termsAndConditions = changeTermsAndConditions();
            var user = userOption(); //convert the function result to the
            var submit = form.submit; //convert the submit button into a variable called submit

            if (purchase && termsAndConditions && user) //if all of these variables are true, proceed
            {
                submit.disabled = false; //enable the submit button
            }
            else
            {
                submit.disabled = true; //disable the submit button
            }
        }

        /*
            this function is used to calculate the price of the products ticked, including delivery
         */
        function productPrice()
        {
            //return all of the checked checkboxes and store them in a variable
            var numberOfCheckboxes = form.querySelectorAll('.item input[type=checkbox]:checked');
            var totalField = form.total; //converts form.total into a variable called totalField
            var price = 0.00; //creates price variable
            var iteration = 0; //creates iteration variable
            var test = false; //creates a test boolean

            //adds the price of each checkbox together and displays it in the total field
            for (iteration; iteration < numberOfCheckboxes.length; iteration += 1)
            {
                var currentCheckBox = numberOfCheckboxes[iteration];

                price = price + parseFloat(currentCheckBox.dataset.price);
            }
            if (numberOfCheckboxes.length > 0) //compares the amount of checkboxes to 0
            {
                price = price + deliveryPrice();
                test = true; //set the variable test to be true
            }
            totalField.value = price.toFixed(2);
            return test; //return test (true)
        }

        /*
            this function calculates the price of the delivery
         */
        function deliveryPrice()
        {
            var price = 0.00; //the overall price of the delivery
            //returns all of the checked radio buttons and stores them in a variable
            var numberOfRadioButtons = form.querySelectorAll('input[type=radio]:checked');
            var iteration;
            //iterates through the amount of radio buttons that have been checked
            for (iteration = 0; iteration < numberOfRadioButtons.length; iteration += 1)
            {
                var currentRadioButton = numberOfRadioButtons[iteration];

                price = price + parseFloat(currentRadioButton.dataset.price);
            }
            return price;
        }
    });
    //]]>
</script>
</body>
</html>